export enum MpdCommands {
  ADD_DIR = "ADD_DIR",
  ADD_PLAYLIST = "ADD_PLAYLIST",
  ADD_PLAY_TRACK = "ADD_PLAY_TRACK",
  ADD_TRACK = "ADD_TRACK",
  BLACKLIST_COVER = "BLACKLIST_COVER",
  PLAY_TRACK = "PLAY_TRACK",
  RM_TRACK = "RM_TRACK",
  SET_SEEK = "SET_SEEK",
  SET_VOLUME = "SET_VOLUME",
  TOGGLE_CONTROL = "TOGGLE_CONTROL",
}
